### ISSUE TITLE
Release 1.17 to Curseforge 

### ISSUE THREAD

**Issue by CodeF53** [comp500/BorderlessMining#13]
I built the 1.17 branch yesterday and have experienced no issues. 

How come it isnt released yet?

**Comment by comp500** [comment]
It isn't finished. In particular, I want to fix a few of the issues users are having with overlays and performance, with some patches to GLFW. I also have been migrating to a custom config GUI rather than cloth config, and I want to bundle fabric-resource-loader with the mod so that Fabric API isn't required.

**Comment by NebelNidas** [comment]
Can't you release a straight-forward port first, so we at least have something to work with, and release your fix as a separate release later on? Even if there are some issues present in the old version, it's better than not having this mod at all 🤔

**Comment by NebelNidas** [comment]
@comp500
