### ISSUE TITLE
Adding the borderless mod cuts performance in half...

### ISSUE THREAD

**Issue by ghost** [comp500/BorderlessMining#20]
Big performance hit ~140 fps down to around 60 fps

Using borderless mining 1.1.1-1.18
fabric-api 44.0
sodium 0.4.0 alpha 5

before adding borderless
![without-borderless](https://user-images.githubusercontent.com/82549089/144735702-c53a07c4-99a9-4c9a-ac8c-e696363208b3.png)

after adding it
![with-borderless](https://user-images.githubusercontent.com/82549089/144735704-e1a34f68-9e5b-46bc-947e-a981a23be063.png)

You can see a big increase  in the proportion of the  updateDisplay (light blue) part of the pie chart

**Comment by comp500** [comment]
Unfortunately it's unlikely that I'll be able to do anything about this - windowed borderless is fundamentally slower since it has to pass through the compositor.

Convincing Windows to enable Fullscreen Optimisations (a middle-ground between exclusive and windowed borderless) might help, and it's possible that the changes in #19 will do that. But I don't really know; fullscreen/borderless window detection is built on a bunch of broken heuristics that vary between graphics drivers, where there's often no way to get it to do what you want.

**Comment by ghost** [comment]
Largely improved in newer versions, closing ticket
